package com.huigu.phone10.mobile

/**
 * MiniMax 全部系统音色数据，按语言分组。
 * 数据来源：MiniMax 官方文档 system-voice-id。
 * 每条包含 voice_id（API 参数）和显示名（官方名称）。
 */

data class MiniMaxVoice(val voiceId: String, val displayName: String)
data class VoiceGroup(val language: String, val voices: List<MiniMaxVoice>)

// 全部 327 个系统音色，按语言分组
val MINIMAX_VOICE_GROUPS: List<VoiceGroup> = listOf(
    VoiceGroup("中文·普通话", listOf(
        MiniMaxVoice("male-qn-qingse", "青涩青年音色"),
        MiniMaxVoice("male-qn-jingying", "精英青年音色"),
        MiniMaxVoice("male-qn-badao", "霸道青年音色"),
        MiniMaxVoice("male-qn-daxuesheng", "青年大学生音色"),
        MiniMaxVoice("female-shaonv", "少女音色"),
        MiniMaxVoice("female-yujie", "御姐音色"),
        MiniMaxVoice("female-chengshu", "成熟女性音色"),
        MiniMaxVoice("female-tianmei", "甜美女性音色"),
        MiniMaxVoice("male-qn-qingse-jingpin", "青涩青年音色-beta"),
        MiniMaxVoice("male-qn-jingying-jingpin", "精英青年音色-beta"),
        MiniMaxVoice("male-qn-badao-jingpin", "霸道青年音色-beta"),
        MiniMaxVoice("male-qn-daxuesheng-jingpin", "青年大学生音色-beta"),
        MiniMaxVoice("female-shaonv-jingpin", "少女音色-beta"),
        MiniMaxVoice("female-yujie-jingpin", "御姐音色-beta"),
        MiniMaxVoice("female-chengshu-jingpin", "成熟女性音色-beta"),
        MiniMaxVoice("female-tianmei-jingpin", "甜美女性音色-beta"),
        MiniMaxVoice("clever_boy", "聪明男童"),
        MiniMaxVoice("cute_boy", "可爱男童"),
        MiniMaxVoice("lovely_girl", "萌萌女童"),
        MiniMaxVoice("cartoon_pig", "卡通猪小琪"),
        MiniMaxVoice("bingjiao_didi", "病娇弟弟"),
        MiniMaxVoice("junlang_nanyou", "俊朗男友"),
        MiniMaxVoice("chunzhen_xuedi", "纯真学弟"),
        MiniMaxVoice("lengdan_xiongzhang", "冷淡学长"),
        MiniMaxVoice("badao_shaoye", "霸道少爷"),
        MiniMaxVoice("tianxin_xiaoling", "甜心小玲"),
        MiniMaxVoice("qiaopi_mengmei", "俏皮萌妹"),
        MiniMaxVoice("wumei_yujie", "妩媚御姐"),
        MiniMaxVoice("diadia_xuemei", "嗲嗲学妹"),
        MiniMaxVoice("danya_xuejie", "淡雅学姐"),
        MiniMaxVoice("Chinese (Mandarin)_Reliable_Executive", "沉稳高管"),
        MiniMaxVoice("Chinese (Mandarin)_News_Anchor", "新闻女声"),
        MiniMaxVoice("Chinese (Mandarin)_Mature_Woman", "傲娇御姐"),
        MiniMaxVoice("Chinese (Mandarin)_Unrestrained_Young_Man", "不羁青年"),
        MiniMaxVoice("Arrogant_Miss", "嚣张小姐"),
        MiniMaxVoice("Robot_Armor", "机械战甲"),
        MiniMaxVoice("Chinese (Mandarin)_Kind-hearted_Antie", "热心大婶"),
        MiniMaxVoice("Chinese (Mandarin)_HK_Flight_Attendant", "港普空姐"),
        MiniMaxVoice("Chinese (Mandarin)_Humorous_Elder", "搞笑大爷"),
        MiniMaxVoice("Chinese (Mandarin)_Gentleman", "温润男声"),
        MiniMaxVoice("Chinese (Mandarin)_Warm_Bestie", "温暖闺蜜"),
        MiniMaxVoice("Chinese (Mandarin)_Male_Announcer", "播报男声"),
        MiniMaxVoice("Chinese (Mandarin)_Sweet_Lady", "甜美女声"),
        MiniMaxVoice("Chinese (Mandarin)_Southern_Young_Man", "南方小哥"),
        MiniMaxVoice("Chinese (Mandarin)_Wise_Women", "阅历姐姐"),
        MiniMaxVoice("Chinese (Mandarin)_Gentle_Youth", "温润青年"),
        MiniMaxVoice("Chinese (Mandarin)_Warm_Girl", "温暖少女"),
        MiniMaxVoice("Chinese (Mandarin)_Kind-hearted_Elder", "花甲奶奶"),
        MiniMaxVoice("Chinese (Mandarin)_Cute_Spirit", "憨憨萌兽"),
        MiniMaxVoice("Chinese (Mandarin)_Radio_Host", "电台男主播"),
        MiniMaxVoice("Chinese (Mandarin)_Lyrical_Voice", "抒情男声"),
        MiniMaxVoice("Chinese (Mandarin)_Straightforward_Boy", "率真弟弟"),
        MiniMaxVoice("Chinese (Mandarin)_Sincere_Adult", "真诚青年"),
        MiniMaxVoice("Chinese (Mandarin)_Gentle_Senior", "温柔学姐"),
        MiniMaxVoice("Chinese (Mandarin)_Stubborn_Friend", "嘴硬竹马"),
        MiniMaxVoice("Chinese (Mandarin)_Crisp_Girl", "清脆少女"),
        MiniMaxVoice("Chinese (Mandarin)_Pure-hearted_Boy", "清澈邻家弟弟"),
        MiniMaxVoice("Chinese (Mandarin)_Soft_Girl", "软软女孩"),
    )),
    VoiceGroup("中文·粤语", listOf(
        MiniMaxVoice("Cantonese_ProfessionalHost（F)", "专业女主持"),
        MiniMaxVoice("Cantonese_GentleLady", "温柔女声"),
        MiniMaxVoice("Cantonese_ProfessionalHost（M)", "专业男主持"),
        MiniMaxVoice("Cantonese_PlayfulMan", "活泼男声"),
        MiniMaxVoice("Cantonese_CuteGirl", "可爱女孩"),
        MiniMaxVoice("Cantonese_KindWoman", "善良女声"),
    )),
    VoiceGroup("英文", listOf(
        MiniMaxVoice("Santa_Claus", "Santa Claus"),
        MiniMaxVoice("Grinch", "Grinch"),
        MiniMaxVoice("Rudolph", "Rudolph"),
        MiniMaxVoice("Arnold", "Arnold"),
        MiniMaxVoice("Charming_Santa", "Charming Santa"),
        MiniMaxVoice("Charming_Lady", "Charming Lady"),
        MiniMaxVoice("Sweet_Girl", "Sweet Girl"),
        MiniMaxVoice("Cute_Elf", "Cute Elf"),
        MiniMaxVoice("Attractive_Girl", "Attractive Girl"),
        MiniMaxVoice("Serene_Woman", "Serene Woman"),
        MiniMaxVoice("English_Trustworthy_Man", "Trustworthy Man"),
        MiniMaxVoice("English_Graceful_Lady", "Graceful Lady"),
        MiniMaxVoice("English_Aussie_Bloke", "Aussie Bloke"),
        MiniMaxVoice("English_Whispering_girl", "Whispering girl"),
        MiniMaxVoice("English_Diligent_Man", "Diligent Man"),
        MiniMaxVoice("English_Gentle-voiced_man", "Gentle-voiced man"),
    )),
    VoiceGroup("日文", listOf(
        MiniMaxVoice("Japanese_IntellectualSenior", "Intellectual Senior"),
        MiniMaxVoice("Japanese_DecisivePrincess", "Decisive Princess"),
        MiniMaxVoice("Japanese_LoyalKnight", "Loyal Knight"),
        MiniMaxVoice("Japanese_DominantMan", "Dominant Man"),
        MiniMaxVoice("Japanese_SeriousCommander", "Serious Commander"),
        MiniMaxVoice("Japanese_ColdQueen", "Cold Queen"),
        MiniMaxVoice("Japanese_DependableWoman", "Dependable Woman"),
        MiniMaxVoice("Japanese_GentleButler", "Gentle Butler"),
        MiniMaxVoice("Japanese_KindLady", "Kind Lady"),
        MiniMaxVoice("Japanese_CalmLady", "Calm Lady"),
        MiniMaxVoice("Japanese_OptimisticYouth", "Optimistic Youth"),
        MiniMaxVoice("Japanese_GenerousIzakayaOwner", "Generous Izakaya Owner"),
        MiniMaxVoice("Japanese_SportyStudent", "Sporty Student"),
        MiniMaxVoice("Japanese_InnocentBoy", "Innocent Boy"),
        MiniMaxVoice("Japanese_GracefulMaiden", "Graceful Maiden"),
    )),
    VoiceGroup("韩文", listOf(
        MiniMaxVoice("Korean_SweetGirl", "Sweet Girl"),
        MiniMaxVoice("Korean_CheerfulBoyfriend", "Cheerful Boyfriend"),
        MiniMaxVoice("Korean_EnchantingSister", "Enchanting Sister"),
        MiniMaxVoice("Korean_ShyGirl", "Shy Girl"),
        MiniMaxVoice("Korean_ReliableSister", "Reliable Sister"),
        MiniMaxVoice("Korean_StrictBoss", "Strict Boss"),
        MiniMaxVoice("Korean_SassyGirl", "Sassy Girl"),
        MiniMaxVoice("Korean_ChildhoodFriendGirl", "Childhood Friend Girl"),
        MiniMaxVoice("Korean_PlayboyCharmer", "Playboy Charmer"),
        MiniMaxVoice("Korean_ElegantPrincess", "Elegant Princess"),
        MiniMaxVoice("Korean_BraveFemaleWarrior", "Brave Female Warrior"),
        MiniMaxVoice("Korean_BraveYouth", "Brave Youth"),
        MiniMaxVoice("Korean_CalmLady", "Calm Lady"),
        MiniMaxVoice("Korean_EnthusiasticTeen", "Enthusiastic Teen"),
        MiniMaxVoice("Korean_SoothingLady", "Soothing Lady"),
        MiniMaxVoice("Korean_IntellectualSenior", "Intellectual Senior"),
        MiniMaxVoice("Korean_LonelyWarrior", "Lonely Warrior"),
        MiniMaxVoice("Korean_MatureLady", "Mature Lady"),
        MiniMaxVoice("Korean_InnocentBoy", "Innocent Boy"),
        MiniMaxVoice("Korean_CharmingSister", "Charming Sister"),
        MiniMaxVoice("Korean_AthleticStudent", "Athletic Student"),
        MiniMaxVoice("Korean_BraveAdventurer", "Brave Adventurer"),
        MiniMaxVoice("Korean_CalmGentleman", "Calm Gentleman"),
        MiniMaxVoice("Korean_WiseElf", "Wise Elf"),
        MiniMaxVoice("Korean_CheerfulCoolJunior", "Cheerful Cool Junior"),
        MiniMaxVoice("Korean_DecisiveQueen", "Decisive Queen"),
        MiniMaxVoice("Korean_ColdYoungMan", "Cold Young Man"),
        MiniMaxVoice("Korean_MysteriousGirl", "Mysterious Girl"),
        MiniMaxVoice("Korean_QuirkyGirl", "Quirky Girl"),
        MiniMaxVoice("Korean_ConsiderateSenior", "Considerate Senior"),
        MiniMaxVoice("Korean_CheerfulLittleSister", "Cheerful Little Sister"),
        MiniMaxVoice("Korean_DominantMan", "Dominant Man"),
        MiniMaxVoice("Korean_AirheadedGirl", "Airheaded Girl"),
        MiniMaxVoice("Korean_ReliableYouth", "Reliable Youth"),
        MiniMaxVoice("Korean_FriendlyBigSister", "Friendly Big Sister"),
        MiniMaxVoice("Korean_GentleBoss", "Gentle Boss"),
        MiniMaxVoice("Korean_ColdGirl", "Cold Girl"),
        MiniMaxVoice("Korean_HaughtyLady", "Haughty Lady"),
        MiniMaxVoice("Korean_CharmingElderSister", "Charming Elder Sister"),
        MiniMaxVoice("Korean_IntellectualMan", "Intellectual Man"),
        MiniMaxVoice("Korean_CaringWoman", "Caring Woman"),
        MiniMaxVoice("Korean_WiseTeacher", "Wise Teacher"),
        MiniMaxVoice("Korean_ConfidentBoss", "Confident Boss"),
        MiniMaxVoice("Korean_AthleticGirl", "Athletic Girl"),
        MiniMaxVoice("Korean_PossessiveMan", "Possessive Man"),
        MiniMaxVoice("Korean_GentleWoman", "Gentle Woman"),
        MiniMaxVoice("Korean_CockyGuy", "Cocky Guy"),
        MiniMaxVoice("Korean_ThoughtfulWoman", "Thoughtful Woman"),
        MiniMaxVoice("Korean_OptimisticYouth", "Optimistic Youth"),
    )),
    VoiceGroup("西班牙文", listOf(
        MiniMaxVoice("Spanish_SereneWoman", "Serene Woman"),
        MiniMaxVoice("Spanish_MaturePartner", "Mature Partner"),
        MiniMaxVoice("Spanish_CaptivatingStoryteller", "Captivating Storyteller"),
        MiniMaxVoice("Spanish_Narrator", "Narrator"),
        MiniMaxVoice("Spanish_WiseScholar", "Wise Scholar"),
        MiniMaxVoice("Spanish_Kind-heartedGirl", "Kind-hearted Girl"),
        MiniMaxVoice("Spanish_DeterminedManager", "Determined Manager"),
        MiniMaxVoice("Spanish_BossyLeader", "Bossy Leader"),
        MiniMaxVoice("Spanish_ReservedYoungMan", "Reserved Young Man"),
        MiniMaxVoice("Spanish_ConfidentWoman", "Confident Woman"),
        MiniMaxVoice("Spanish_ThoughtfulMan", "Thoughtful Man"),
        MiniMaxVoice("Spanish_Strong-WilledBoy", "Strong-willed Boy"),
        MiniMaxVoice("Spanish_SophisticatedLady", "Sophisticated Lady"),
        MiniMaxVoice("Spanish_RationalMan", "Rational Man"),
        MiniMaxVoice("Spanish_AnimeCharacter", "Anime Character"),
        MiniMaxVoice("Spanish_Deep-tonedMan", "Deep-toned Man"),
        MiniMaxVoice("Spanish_Fussyhostess", "Fussy hostess"),
        MiniMaxVoice("Spanish_SincereTeen", "Sincere Teen"),
        MiniMaxVoice("Spanish_FrankLady", "Frank Lady"),
        MiniMaxVoice("Spanish_Comedian", "Comedian"),
        MiniMaxVoice("Spanish_Debator", "Debator"),
        MiniMaxVoice("Spanish_ToughBoss", "Tough Boss"),
        MiniMaxVoice("Spanish_Wiselady", "Wise Lady"),
        MiniMaxVoice("Spanish_Steadymentor", "Steady Mentor"),
        MiniMaxVoice("Spanish_Jovialman", "Jovial Man"),
        MiniMaxVoice("Spanish_SantaClaus", "Santa Claus"),
        MiniMaxVoice("Spanish_Rudolph", "Rudolph"),
        MiniMaxVoice("Spanish_Intonategirl", "Intonate Girl"),
        MiniMaxVoice("Spanish_Arnold", "Arnold"),
        MiniMaxVoice("Spanish_Ghost", "Ghost"),
        MiniMaxVoice("Spanish_HumorousElder", "Humorous Elder"),
        MiniMaxVoice("Spanish_EnergeticBoy", "Energetic Boy"),
        MiniMaxVoice("Spanish_WhimsicalGirl", "Whimsical Girl"),
        MiniMaxVoice("Spanish_StrictBoss", "Strict Boss"),
        MiniMaxVoice("Spanish_ReliableMan", "Reliable Man"),
        MiniMaxVoice("Spanish_SereneElder", "Serene Elder"),
        MiniMaxVoice("Spanish_AngryMan", "Angry Man"),
        MiniMaxVoice("Spanish_AssertiveQueen", "Assertive Queen"),
        MiniMaxVoice("Spanish_CaringGirlfriend", "Caring Girlfriend"),
        MiniMaxVoice("Spanish_PowerfulSoldier", "Powerful Soldier"),
        MiniMaxVoice("Spanish_PassionateWarrior", "Passionate Warrior"),
        MiniMaxVoice("Spanish_ChattyGirl", "Chatty Girl"),
        MiniMaxVoice("Spanish_RomanticHusband", "Romantic Husband"),
        MiniMaxVoice("Spanish_CompellingGirl", "Compelling Girl"),
        MiniMaxVoice("Spanish_PowerfulVeteran", "Powerful Veteran"),
        MiniMaxVoice("Spanish_SensibleManager", "Sensible Manager"),
        MiniMaxVoice("Spanish_ThoughtfulLady", "Thoughtful Lady"),
    )),
    VoiceGroup("葡萄牙文", listOf(
        MiniMaxVoice("Portuguese_SentimentalLady", "Sentimental Lady"),
        MiniMaxVoice("Portuguese_BossyLeader", "Bossy Leader"),
        MiniMaxVoice("Portuguese_Wiselady", "Wise lady"),
        MiniMaxVoice("Portuguese_Strong-WilledBoy", "Strong-willed Boy"),
        MiniMaxVoice("Portuguese_Deep-VoicedGentleman", "Deep-voiced Gentleman"),
        MiniMaxVoice("Portuguese_UpsetGirl", "Upset Girl"),
        MiniMaxVoice("Portuguese_PassionateWarrior", "Passionate Warrior"),
        MiniMaxVoice("Portuguese_AnimeCharacter", "Anime Character"),
        MiniMaxVoice("Portuguese_ConfidentWoman", "Confident Woman"),
        MiniMaxVoice("Portuguese_AngryMan", "Angry Man"),
        MiniMaxVoice("Portuguese_CaptivatingStoryteller", "Captivating Storyteller"),
        MiniMaxVoice("Portuguese_Godfather", "Godfather"),
        MiniMaxVoice("Portuguese_ReservedYoungMan", "Reserved Young Man"),
        MiniMaxVoice("Portuguese_SmartYoungGirl", "Smart Young Girl"),
        MiniMaxVoice("Portuguese_Kind-heartedGirl", "Kind-hearted Girl"),
        MiniMaxVoice("Portuguese_Pompouslady", "Pompous lady"),
        MiniMaxVoice("Portuguese_Grinch", "Grinch"),
        MiniMaxVoice("Portuguese_Debator", "Debator"),
        MiniMaxVoice("Portuguese_SweetGirl", "Sweet Girl"),
        MiniMaxVoice("Portuguese_AttractiveGirl", "Attractive Girl"),
        MiniMaxVoice("Portuguese_ThoughtfulMan", "Thoughtful Man"),
        MiniMaxVoice("Portuguese_PlayfulGirl", "Playful Girl"),
        MiniMaxVoice("Portuguese_GorgeousLady", "Gorgeous Lady"),
        MiniMaxVoice("Portuguese_LovelyLady", "Lovely Lady"),
        MiniMaxVoice("Portuguese_SereneWoman", "Serene Woman"),
        MiniMaxVoice("Portuguese_SadTeen", "Sad Teen"),
        MiniMaxVoice("Portuguese_MaturePartner", "Mature Partner"),
        MiniMaxVoice("Portuguese_Comedian", "Comedian"),
        MiniMaxVoice("Portuguese_NaughtySchoolgirl", "Naughty Schoolgirl"),
        MiniMaxVoice("Portuguese_Narrator", "Narrator"),
        MiniMaxVoice("Portuguese_ToughBoss", "Tough Boss"),
        MiniMaxVoice("Portuguese_Fussyhostess", "Fussy hostess"),
        MiniMaxVoice("Portuguese_Dramatist", "Dramatist"),
        MiniMaxVoice("Portuguese_Steadymentor", "Steady Mentor"),
        MiniMaxVoice("Portuguese_Jovialman", "Jovial Man"),
        MiniMaxVoice("Portuguese_CharmingQueen", "Charming Queen"),
        MiniMaxVoice("Portuguese_SantaClaus", "Santa Claus"),
        MiniMaxVoice("Portuguese_Rudolph", "Rudolph"),
        MiniMaxVoice("Portuguese_Arnold", "Arnold"),
        MiniMaxVoice("Portuguese_CharmingSanta", "Charming Santa"),
        MiniMaxVoice("Portuguese_CharmingLady", "Charming Lady"),
        MiniMaxVoice("Portuguese_Ghost", "Ghost"),
        MiniMaxVoice("Portuguese_HumorousElder", "Humorous Elder"),
        MiniMaxVoice("Portuguese_CalmLeader", "Calm Leader"),
        MiniMaxVoice("Portuguese_GentleTeacher", "Gentle Teacher"),
        MiniMaxVoice("Portuguese_EnergeticBoy", "Energetic Boy"),
        MiniMaxVoice("Portuguese_ReliableMan", "Reliable Man"),
        MiniMaxVoice("Portuguese_SereneElder", "Serene Elder"),
        MiniMaxVoice("Portuguese_GrimReaper", "Grim Reaper"),
        MiniMaxVoice("Portuguese_AssertiveQueen", "Assertive Queen"),
        MiniMaxVoice("Portuguese_WhimsicalGirl", "Whimsical Girl"),
        MiniMaxVoice("Portuguese_StressedLady", "Stressed Lady"),
        MiniMaxVoice("Portuguese_FriendlyNeighbor", "Friendly Neighbor"),
        MiniMaxVoice("Portuguese_CaringGirlfriend", "Caring Girlfriend"),
        MiniMaxVoice("Portuguese_PowerfulSoldier", "Powerful Soldier"),
        MiniMaxVoice("Portuguese_FascinatingBoy", "Fascinating Boy"),
        MiniMaxVoice("Portuguese_RomanticHusband", "Romantic Husband"),
        MiniMaxVoice("Portuguese_StrictBoss", "Strict Boss"),
        MiniMaxVoice("Portuguese_InspiringLady", "Inspiring Lady"),
        MiniMaxVoice("Portuguese_PlayfulSpirit", "Playful Spirit"),
        MiniMaxVoice("Portuguese_ElegantGirl", "Elegant Girl"),
        MiniMaxVoice("Portuguese_CompellingGirl", "Compelling Girl"),
        MiniMaxVoice("Portuguese_PowerfulVeteran", "Powerful Veteran"),
        MiniMaxVoice("Portuguese_SensibleManager", "Sensible Manager"),
        MiniMaxVoice("Portuguese_ThoughtfulLady", "Thoughtful Lady"),
        MiniMaxVoice("Portuguese_TheatricalActor", "Theatrical Actor"),
        MiniMaxVoice("Portuguese_FragileBoy", "Fragile Boy"),
        MiniMaxVoice("Portuguese_ChattyGirl", "Chatty Girl"),
        MiniMaxVoice("Portuguese_Conscientiousinstructor", "Conscientious Instructor"),
        MiniMaxVoice("Portuguese_RationalMan", "Rational Man"),
        MiniMaxVoice("Portuguese_WiseScholar", "Wise Scholar"),
        MiniMaxVoice("Portuguese_FrankLady", "Frank Lady"),
        MiniMaxVoice("Portuguese_DeterminedManager", "Determined Manager"),
    )),
    VoiceGroup("法文", listOf(
        MiniMaxVoice("French_Male_Speech_New", "Level-Headed Man"),
        MiniMaxVoice("French_Female_News Anchor", "Patient Female Presenter"),
        MiniMaxVoice("French_CasualMan", "Casual Man"),
        MiniMaxVoice("French_MovieLeadFemale", "Movie Lead Female"),
        MiniMaxVoice("French_FemaleAnchor", "Female Anchor"),
        MiniMaxVoice("French_MaleNarrator", "Male Narrator"),
    )),
    VoiceGroup("印尼文", listOf(
        MiniMaxVoice("Indonesian_SweetGirl", "Sweet Girl"),
        MiniMaxVoice("Indonesian_ReservedYoungMan", "Reserved Young Man"),
        MiniMaxVoice("Indonesian_CharmingGirl", "Charming Girl"),
        MiniMaxVoice("Indonesian_CalmWoman", "Calm Woman"),
        MiniMaxVoice("Indonesian_ConfidentWoman", "Confident Woman"),
        MiniMaxVoice("Indonesian_CaringMan", "Caring Man"),
        MiniMaxVoice("Indonesian_BossyLeader", "Bossy Leader"),
        MiniMaxVoice("Indonesian_DeterminedBoy", "Determined Boy"),
        MiniMaxVoice("Indonesian_GentleGirl", "Gentle Girl"),
    )),
    VoiceGroup("德文", listOf(
        MiniMaxVoice("German_FriendlyMan", "Friendly Man"),
        MiniMaxVoice("German_SweetLady", "Sweet Lady"),
        MiniMaxVoice("German_PlayfulMan", "Playful Man"),
    )),
    VoiceGroup("俄文", listOf(
        MiniMaxVoice("Russian_HandsomeChildhoodFriend", "Handsome Childhood Friend"),
        MiniMaxVoice("Russian_BrightHeroine", "Bright Queen"),
        MiniMaxVoice("Russian_AmbitiousWoman", "Ambitious Woman"),
        MiniMaxVoice("Russian_ReliableMan", "Reliable Man"),
        MiniMaxVoice("Russian_CrazyQueen", "Crazy Girl"),
        MiniMaxVoice("Russian_PessimisticGirl", "Pessimistic Girl"),
        MiniMaxVoice("Russian_AttractiveGuy", "Attractive Guy"),
        MiniMaxVoice("Russian_Bad-temperedBoy", "Bad-tempered Boy"),
    )),
    VoiceGroup("意大利文", listOf(
        MiniMaxVoice("Italian_BraveHeroine", "Brave Heroine"),
        MiniMaxVoice("Italian_Narrator", "Narrator"),
        MiniMaxVoice("Italian_WanderingSorcerer", "Wandering Sorcerer"),
        MiniMaxVoice("Italian_DiligentLeader", "Diligent Leader"),
    )),
    VoiceGroup("阿拉伯文", listOf(
        MiniMaxVoice("Arabic_CalmWoman", "Calm Woman"),
        MiniMaxVoice("Arabic_FriendlyGuy", "Friendly Guy"),
    )),
    VoiceGroup("土耳其文", listOf(
        MiniMaxVoice("Turkish_CalmWoman", "Calm Woman"),
        MiniMaxVoice("Turkish_Trustworthyman", "Trustworthy man"),
    )),
    VoiceGroup("乌克兰文", listOf(
        MiniMaxVoice("Ukrainian_CalmWoman", "Calm Woman"),
        MiniMaxVoice("Ukrainian_WiseScholar", "Wise Scholar"),
    )),
    VoiceGroup("荷兰文", listOf(
        MiniMaxVoice("Dutch_kindhearted_girl", "Kind-hearted girl"),
        MiniMaxVoice("Dutch_bossy_leader", "Bossy leader"),
    )),
    VoiceGroup("越南文", listOf(
        MiniMaxVoice("Vietnamese_kindhearted_girl", "Kind-hearted girl"),
    )),
    VoiceGroup("泰文", listOf(
        MiniMaxVoice("Thai_male_1_sample8", "Serene Man"),
        MiniMaxVoice("Thai_male_2_sample2", "Friendly Man"),
        MiniMaxVoice("Thai_female_1_sample1", "Confident Woman"),
        MiniMaxVoice("Thai_female_2_sample2", "Energetic Woman"),
    )),
    VoiceGroup("波兰文", listOf(
        MiniMaxVoice("Polish_male_1_sample4", "Male Narrator"),
        MiniMaxVoice("Polish_male_2_sample3", "Male Anchor"),
        MiniMaxVoice("Polish_female_1_sample1", "Calm Woman"),
        MiniMaxVoice("Polish_female_2_sample3", "Casual Woman"),
    )),
    VoiceGroup("罗马尼亚文", listOf(
        MiniMaxVoice("Romanian_male_1_sample2", "Reliable Man"),
        MiniMaxVoice("Romanian_male_2_sample1", "Energetic Youth"),
        MiniMaxVoice("Romanian_female_1_sample4", "Optimistic Youth"),
        MiniMaxVoice("Romanian_female_2_sample1", "Gentle Woman"),
    )),
    VoiceGroup("希腊文", listOf(
        MiniMaxVoice("greek_male_1a_v1", "Thoughtful Mentor"),
        MiniMaxVoice("Greek_female_1_sample1", "Gentle Lady"),
        MiniMaxVoice("Greek_female_2_sample3", "Girl Next Door"),
    )),
    VoiceGroup("捷克文", listOf(
        MiniMaxVoice("czech_male_1_v1", "Assured Presenter"),
        MiniMaxVoice("czech_female_5_v7", "Steadfast Narrator"),
        MiniMaxVoice("czech_female_2_v2", "Elegant Lady"),
    )),
    VoiceGroup("芬兰文", listOf(
        MiniMaxVoice("finnish_male_3_v1", "Upbeat Man"),
        MiniMaxVoice("finnish_male_1_v2", "Friendly Boy"),
        MiniMaxVoice("finnish_female_4_v1", "Assetive Woman"),
    )),
    VoiceGroup("印地文", listOf(
        MiniMaxVoice("hindi_male_1_v2", "Trustworthy Advisor"),
        MiniMaxVoice("hindi_female_2_v1", "Tranquil Woman"),
        MiniMaxVoice("hindi_female_1_v2", "News Anchor"),
    )),
)

// 在全部音色中搜索（用于跨语言搜索）
fun findVoice(voiceId: String): MiniMaxVoice? =
    MINIMAX_VOICE_GROUPS.flatMap { it.voices }.firstOrNull { it.voiceId == voiceId }
